version: '3.8'

services:
  frontend:
    image: 'alectrion/repo:front'
    container_name: alectrion_frontend
    # depends_on:
    #   - alectrion_gateway
    environment:
      - REACT_APP_GATEWAY_URL=http://127.0.0.1:4000
    ports:
      - 3000:3000
    command: "yarn dev"
  
  user_db:
    image: postgres
    volumes:
      - user-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user

  user_api:
    image: 'alectrion/repo:user'
    container_name: user_api
    # depends_on:
    #   - user_db
    environment:
      - DB_URL=http://user:postgres@user_db:5432/user
      - SECRET_JWT="95dbfe2790ed50cedae427abc8a49aef"
    ports:
      - 4001:4001
    command:  bash -c "yarn && yarn migration:run && yarn dev"

  equipment_db:
    image: postgres
    volumes:
      - equipment-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=equipment

  equipment_api:
    image: 'alectrion/repo:equipment'
    container_name: alectrion_equipment_api
    depends_on:
      - equipment_db
    environment:
      - DB_URL=http://user:postgres@equipment_db:5432/equipment
      - SECRET_JWT=95dbfe2790ed50cedae427abc8a49aef
    ports:
      - 4002:4002
    command:  bash -c "yarn && yarn migration:run && yarn dev"
  gateway:
    image: 'alectrion/repo:gateway'
    container_name: alectrion_gateway
    # depends_on:
    #   - alectrion_equipment_api
    #   - alectrion_user_api
    environment:
      - USER_URL=http://user_api:4001
      - EQUIP_URL=http://equipment_api:4002
      - PORT=4000
    ports:
      - 4000:4000
    command:  bash -c "yarn dev"

volumes:
  user-data:
  equipment-data: