version: '3'

services:
  # postgres db
  db:
    # image: postgres:latest
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  # Check if postgres is ready
  wait-for-db:
    image: alpine:latest
    command: /bin/sh -c "apk add --no-cache postgresql-client && until pg_isready -h db -p 5432 -U postgres; do sleep 1; done;"
    depends_on:
      db:
        condition: service_healthy