use api_roles_db

db.roles.drop()

db.roles.insert(
[
{ "name": "ADVOGADO (IQUEGO)", "description": "OUTRO ÓRGÃO - ADVOGADO - CLT - CONTRATADO" },
{ "name": "AGENTE ADMINISTRATIVO B VI - AGECOM", "description": "OUTRO ÓRGÃO - Agente Administrativo B VI - AGECOM - CLT - CONTRATADO" },
{ "name": "AGENTE ADMINISTRATIVO EDUCACIONAL DE APOIO", "description": "OUTRO ÓRGÃO - AGENTE ADMINISTRATIVO EDUCACIONAL DE APOIO - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE AUXILIAR DE ADMINISTRAÇÃO II (AGECOM)", "description": "OUTRO ÓRGÃO - AGENTE AUXILIAR DE ADMINISTRAÇÃO II (AGECOM) - CLT - CONTRATADO" },
{ "name": "AGENTE AUXILIAR POLICIAL", "description": "POLICIAL - DGPC/GO - AGENTE AUXILIAR POLICIAL - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE NECROTOMIA - TOCANTINS", "description": "OUTRO ÓRGÃO - AGENTE DE NECROTOMIA - TOCANTINS - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE POLÍCIA DA 1ª CLASSE", "description": "POLICIAL - DGPC/GO - Agente De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE POLÍCIA DA 2ª CLASSE", "description": "POLICIAL - DGPC/GO - Agente De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE POLÍCIA DA 3ª CLASSE", "description": "POLICIAL - DGPC/GO - Agente De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE POLÍCIA DA CLASSE ESPECIAL", "description": "POLICIAL - DGPC/GO - Agente De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE POLÍCIA DA CLASSE ESPECIAL I", "description": "POLICIAL - DGPC/GO - Agente De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE POLÍCIA DO TOCANTINS - CLASSE ESPECIAL", "description": "OUTRO ÓRGÃO - AGENTE DE POLÍCIA - TOCANTINS - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE DE POLÍCIA JUDICIÁRIA - SSP/MATO GROSSO DO SUL", "description": "OUTRO ÓRGÃO - AGENTE DE POLÍCIA JUDICIÁRIA - SSP/MATO GROSSO DO SUL - ESTATUTÁRIO - DISPOSIÇÃO PARA  DGPC" },
{ "name": "AGENTE DE SEGURANÇA PRISIONAL", "description": "OUTRO ÓRGÃO - AGENTE DE SEGURANÇA PRISIONAL - ESTATUTÁRIO - DISPOSIÇÃO PARA  DGPC" },
{ "name": "AGENTE DE VIGILÂNCIA", "description": "OUTRO ÓRGÃO - Agente de Vigilância - ESTATUTÁRIO - EFETIVO" },
{ "name": "AGENTE POLICIAL", "description": "POLICIAL - DGPC/GO - AGENTE POLICIAL - ESTATUTÁRIO - EFETIVO" },
{ "name": "ANALISTA DE COMUNICAÇÃO", "description": "OUTRO ÓRGÃO - Analista de Comunicação - ESTATUTÁRIO - EFETIVO" },
{ "name": "ANALISTA DE DESENVOLVIMENTO RURAL", "description": "OUTRO ÓRGÃO - ANALISTA DE DESENVOLVIMENTO RURAL - CLT - CONTRATADO" },
{ "name": "ANALISTA DE GESTÃO ADMINISTRATIVA", "description": "OUTRO ÓRGÃO - ANALISTA DE GESTÃO ADMINISTRATIVA - ESTATUTÁRIO - EFETIVO" },
{ "name": "ANALISTA DE GESTÃO GOVERNAMENTAL", "description": "OUTRO ÓRGÃO - Analista de Gestão Governamental - ESTATUTÁRIO - EFETIVO" },
{ "name": "Analista De Politicas De Assistencia Social", "description": "OUTRO ÓRGÃO - ANALISTA DE POLITICAS DE ASSISTENCIA SOCIAL - ESTATUTÁRIO - EFETIVO" },
{ "name": "ARMAZENADOR - IQUEGO", "description": "OUTRO ÓRGÃO - ARMAZENADOR - IQUEGO - CLT - CONTRATADO" },
{ "name": "ASSESSOR A1", "description": "OUTRO ÓRGÃO - ASSESSOR A1 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR A3", "description": "OUTRO ÓRGÃO - ASSESSOR A3 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR A4", "description": "OUTRO ÓRGÃO - ASSESSOR A4 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR A5", "description": "OUTRO ÓRGÃO - ASSESSOR A5 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR A6", "description": "OUTRO ÓRGÃO - ASSESSOR A6 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR A7", "description": "OUTRO ÓRGÃO - ASSESSOR A7 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR A8", "description": "OUTRO ÓRGÃO - ASSESSOR A8 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR A9", "description": "OUTRO ÓRGÃO - ASSESSOR A9 - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSESSOR TÉCNICO M-1", "description": "OUTRO ÓRGÃO - ASSESSOR TÉCNICO M-1 - ESTATUTÁRIO - EFETIVO" },
{ "name": "ASSISTENTE ADMINISTRATIVO", "description": "OUTRO ÓRGÃO - ASSISTENTE ADMINISTRATIVO - ESTATUTÁRIO - EFETIVO" },
{ "name": "ASSISTENTE DE APOIO ADMINISTRATIVO", "description": "OUTRO ÓRGÃO - ASSISTENTE DE APOIO ADMINISTRATIVO - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "ASSISTENTE DE COMUNICAÇÃO", "description": "OUTRO ÓRGÃO - Assistente de Comunicação - CLT - CONTRATADO" },
{ "name": "ASSISTENTE DE GESTÃO  ADMINISTRATIVA", "description": "OUTRO ÓRGÃO - Assistente de Gestão Administrativa - CLT - EFETIVO" },
{ "name": "ASSISTENTE DE GESTÃO ADMINISTRATIVA", "description": "OUTRO ÓRGÃO - Assistente de Gestão Administrativa - CLT - CONTRATADO" },
{ "name": "ASSISTENTE DE MANUTENÇÃO", "description": "OUTRO ÓRGÃO - ASSISTENTE DE MANUTENÇÃO - CLT - CONTRATADO" },
{ "name": "ASSISTENTE DE TRANSPORTES E OBRAS", "description": "OUTRO ÓRGÃO - ASSISTENTE DE TRANSPORTES E OBRAS - ESTATUTÁRIO - EFETIVO" },
{ "name": "ASSISTENTE INDUSTRIAL", "description": "OUTRO ÓRGÃO - ASSISTENTE INDUSTRIAL  - CLT - CONTRATADO" },
{ "name": "ASSISTENTE OPERACIONAL", "description": "OUTRO ÓRGÃO - ASSISTENTE OPERACIONAL - CLT - CONTRATADO" },
{ "name": "ASSISTENTE OPERACIONAL-SOCIAL", "description": "OUTRO ÓRGÃO - ASSISTENTE OPERACIONAL-SOCIAL - ESTATUTÁRIO - EFETIVO" },
{ "name": "AUXILIAR ADMINISTRATIVO (IQUEGO)", "description": "OUTRO ÓRGÃO - AUXILIAR ADMINISTRATIVO (IQUEGO) - CLT - CONTRATADO" },
{ "name": "AUXILIAR DE ENFERMAGEM", "description": "OUTRO ÓRGÃO - Auxiliar de Enfermagem - ESTATUTÁRIO - EFETIVO" },
{ "name": "AUXILIAR DE GESTÃO  ADMINISTRATIVA", "description": "OUTRO ÓRGÃO - Auxiliar De Gestão Administrativa - CLT - EFETIVO" },
{ "name": "AUXILIAR DE GESTÃO ADMINISTRATIVA", "description": "OUTRO ÓRGÃO - Auxiliar De Gestão Administrativa - ESTATUTÁRIO - EFETIVO" },
{ "name": "AUXILIAR DE SERVIÇOS GERAIS (METROBUS)", "description": "OUTRO ÓRGÃO - AUXILIAR DE SERVIÇOS GERAIS (METROBUS) - CLT - CONTRATADO" },
{ "name": "AUXILIAR DE SERVIÇOS GERAIS (SES)", "description": "OUTRO ÓRGÃO - AUXILIAR DE SERVIÇOS GERAIS (SES) - ESTATUTÁRIO - EFETIVO" },
{ "name": "AUXILIAR INDUSTRIAL", "description": "OUTRO ÓRGÃO - AUXILIAR INDUSTRIAL - CLT - EFETIVO" },
{ "name": "AUXILIAR OPERACIONAL", "description": "OUTRO ÓRGÃO - Auxiliar Operacional - CLT - CONTRATADO" },
{ "name": "AUXILIAR TÉCNICO DE SAÚDE", "description": "OUTRO ÓRGÃO - AUXILIAR TÉCNICO DE SAÚDE - ESTATUTÁRIO - EFETIVO" },
{ "name": "CHAPISTA II", "description": "OUTRO ÓRGÃO - CHAPISTA II - CLT - CONTRATADO" },
{ "name": "DACTILOSCOPISTA", "description": "POLICIAL - DGPC/GO - Grupo Ocupacional de Identificação - ESTATUTÁRIO - EFETIVO" },
{ "name": "DELEGADO DE POLÍCIA CLASSE ESPECIAL", "description": "POLICIAL - DGPC/GO - Delegado De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "DELEGADO DE POLÍCIA CLASSE ESPECIAL I", "description": "POLICIAL - DGPC/GO - Delegado De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "DELEGADO DE POLÍCIA DA 1ª CLASSE", "description": "POLICIAL - DGPC/GO - Delegado De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "DELEGADO DE POLÍCIA DA 2ª CLASSE", "description": "POLICIAL - DGPC/GO - Delegado De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "DELEGADO DE POLÍCIA SUBSTITUTO", "description": "POLICIAL - DGPC/GO - Delegado De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "ELETRICISTA DE AUTOS (METROBUS)", "description": "OUTRO ÓRGÃO - ELETRICISTA DE AUTOS - CLT - CONTRATADO" },
{ "name": "ESCREVENTE POLICIAL", "description": "POLICIAL - DGPC/GO - Escrevente Policial - ESTATUTÁRIO - EFETIVO" },
{ "name": "ESCRITURÁRIO", "description": "OUTRO ÓRGÃO - Escriturário - CLT - EFETIVO" },
{ "name": "ESCRITURÁRIO (METROBUS)", "description": "OUTRO ÓRGÃO - Escriturário - CLT - CONTRATADO" },
{ "name": "ESCRIVÃO DE POLÍCIA DA 1ª CLASSE", "description": "POLICIAL - DGPC/GO - Escrivão De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "ESCRIVÃO DE POLÍCIA DA 2ª CLASSE", "description": "POLICIAL - DGPC/GO - Escrivão De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "ESCRIVÃO DE POLÍCIA DA 3ª CLASSE", "description": "POLICIAL - DGPC/GO - Escrivão De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "ESCRIVÃO DE POLÍCIA DA CLASSE ESPECIAL", "description": "POLICIAL - DGPC/GO - Escrivão De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "ESCRIVÃO DE POLÍCIA DA CLASSE ESPECIAL I", "description": "POLICIAL - DGPC/GO - Escrivão De Polícia - ESTATUTÁRIO - EFETIVO" },
{ "name": "FISCAL DE TRANSPORTE", "description": "OUTRO ÓRGÃO - Fiscal de Transportes - CLT - CONTRATADO" },
{ "name": "FISCAL DE TRANSPORTE COLETIVO", "description": "OUTRO ÓRGÃO - Fiscal de Transportes - CLT - CONTRATADO" },
{ "name": "FISCAL DE TRANSPORTES (METROBUS)", "description": "OUTRO ÓRGÃO - Fiscal de Transportes - CLT - CONTRATADO" },
{ "name": "FOTOCOMPOSITOR IV (AGECOM)", "description": "OUTRO ÓRGÃO - FOTOCOMPOSITOR IV (AGECOM) - CLT - CONTRATADO" },
{ "name": "GESTOR DE PLANEJAMENTO E ORÇAMENTO", "description": "OUTRO ÓRGÃO - GESTOR DE PLANEJAMENTO E ORÇAMENTO - ESTATUTÁRIO - EFETIVO" },
{ "name": "GESTOR DE TECNOLOGIA DA INFORMAÇÃO", "description": "OUTRO ÓRGÃO - GESTOR DE TECNOLOGIA DA INFORMAÇÃO - ESTATUTÁRIO - EFETIVO" },
{ "name": "GESTOR PÚBLICO", "description": "OUTRO ÓRGÃO - GESTOR PÚBLICO - ESTATUTÁRIO - EFETIVO" },
{ "name": "LANTERNEIRO (METROBUS)", "description": "OUTRO ÓRGÃO - LANTERNEIRO (METROBUS) - CLT - CONTRATADO" },
{ "name": "LIDER DE ÁREA OU PROJETO", "description": "OUTRO ÓRGÃO - LÍDER DE ÁREA OU PROJETO - ESTATUTÁRIO - COMISSIONADO" },
{ "name": "MAQUIADOR I (AGECOM)", "description": "OUTRO ÓRGÃO - MAQUIADOR I (AGECOM) - CLT - CONTRATADO" },
{ "name": "MECÂNICO (METROBUS)", "description": "OUTRO ÓRGÃO - MECÂNICO - CLT - CONTRATADO" },
{ "name": "MOTORISTA", "description": "OUTRO ÓRGÃO - MOTORISTA - CLT - CONTRATADO" },
{ "name": "MOTORISTA (METROBUS)", "description": "OUTRO ÓRGÃO - MOTORISTA - CLT - CONTRATADO" },
{ "name": "OPERADOR", "description": "OUTRO ÓRGÃO - OPERADOR - CLT - CONTRATADO" },
{ "name": "OPERADOR (METROBUS)", "description": "OUTRO ÓRGÃO - OPERADOR - CLT - CONTRATADO" },
{ "name": "PAPILOSCOPISTA POLICIAL DA 1ª CLASSE", "description": "POLICIAL - DGPC/GO - Papiloscopista Policial - ESTATUTÁRIO - EFETIVO" },
{ "name": "PAPILOSCOPISTA POLICIAL DA 2ª CLASSE", "description": "POLICIAL - DGPC/GO - Papiloscopista Policial - ESTATUTÁRIO - EFETIVO" },
{ "name": "PAPILOSCOPISTA POLICIAL DA 3ª CLASSE", "description": "POLICIAL - DGPC/GO - Papiloscopista Policial - ESTATUTÁRIO - EFETIVO" },
{ "name": "PAPILOSCOPISTA POLICIAL DA CLASSE ESPECIAL", "description": "POLICIAL - DGPC/GO - Papiloscopista Policial - ESTATUTÁRIO - EFETIVO" },
{ "name": "PINTOR DE AUTOS", "description": "OUTRO ÓRGÃO - PINTOR DE AUTOS - CLT - CONTRATADO" },
{ "name": "PORTEIRO", "description": "OUTRO ÓRGÃO - PORTEIRO - CLT - CONTRATADO" },
{ "name": "TECNICO DE SEGURANÇA DO TRABALHO", "description": "OUTRO ÓRGÃO - TECNICO DE SEGURANÇA DO TRABALHO - CLT - CONTRATADO" },
{ "name": "TÉCNICO EM ENFERMAGEM", "description": "OUTRO ÓRGÃO - TÉCNICO EM ENFERMAGEM - ESTATUTÁRIO - EFETIVO" },
{ "name": "TÉCNICO EM GESTÃO PÚBLICA", "description": "OUTRO ÓRGÃO - Técnico em Gestão Pública - ESTATUTÁRIO - EFETIVO" },
{ "name": "TÉCNICO EM GESTÃO PÚBLICA I", "description": "OUTRO ÓRGÃO - Técnico em Gestão Pública - ESTATUTÁRIO - EFETIVO" }
]
)

