version: '3.8'

services:
  frontend:
    image: ditgo/2020-2-siged-frontend_frontend:latest
    ports: 
      - 3000:3000
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules
    deploy:
      mode: replicated
      replicas: 3

volumes: 
  node_modules:
