\c schedula_location

INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'APARECIDA DE GOIÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GOIÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'FORMOSA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'RIO VERDE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ANÁPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITUMBIARA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'JATAÍ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'LUZIÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CATALÃO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CORUMBAÍBA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CRISTALINA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CRIXÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CROMÍNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'VALPARAÍSO DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NOVO GAMA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PORANGATU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ABADIÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ACREÚNA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ÁGUA FRIA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ÁGUA LIMPA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ALEXÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ALOÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ALTO PARAÍSO DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'AMORINÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ANHANGUERA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'APORÉ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ARAGOIÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ARAGUAPAZ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ARUANÃ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BALIZA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BELA VISTA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BOM JARDIM DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BOM JESUS DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BONFINÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BONÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BRITÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CABECEIRAS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CACHOEIRA ALTA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CACHOEIRA DOURADA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAÇU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'FAINA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAMPESTRE DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAMPINAÇU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAMPO ALEGRE DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAMPOS BELOS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CARMO DO RIO VERDE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAVALCANTE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'COCALZINHO DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CORUMBÁ DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'DAVINÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'DIVINÓPOLIS DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'EDEALINA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'EDÉIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'FAZENDA NOVA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'FLORES DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GOIANÁPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GOIANDIRA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GOIANIRA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'IPAMERI', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ISRAELÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITABERAÍ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITAJÁ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITAGUARU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITAPURANGA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITAUÇU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GOIATUBA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GUARANI DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'HIDROLÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'IACIARA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'INDIARA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'IVOLÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'JAUPACI', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'JARAGUÁ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'JESÚPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'LEOPOLDO DE BULHÕES', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MAMBAÍ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MARZAGÃO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MATRINCHÃ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MAURILÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MINAÇU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MINEIROS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MONTE ALEGRE DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MONTES CLAROS DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MONTIVIDIU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MOSSÂMEDES', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MOZARLÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MUTUNÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NAZÁRIO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NERÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANCLERLÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NOVA VENEZA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ORIZONA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'OURO VERDE DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PADRE BERNARDO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAIAPÔNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PALMELO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PALMINÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PANAMÁ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PARAÚNA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PILAR DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PIRACANJUBA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PIRANHAS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PIRES DO RIO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PONTALINA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PORTEIRÃO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PORTELÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'RIANÁPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'RUBIATABA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTA BÁRBARA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTA CRUZ DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTA HELENA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTA RITA DO ARAGUAIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'TEREZÓPOLIS DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTA TEREZA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTA TEREZINHA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTO ANTÔNIO DA BARRA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÃO FRANCISCO DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÃO LUÍS DE MONTES BELOS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÃO LUIZ DO NORTE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÃO MIGUEL DO PASSA QUATRO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÃO MIGUEL DO ARAGUAIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SENADOR CANEDO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SILVÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÍTIO D´ABADIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'TERESINA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'TRÊS RANCHOS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'TURVÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'URUTAÍ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'VIANÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'IPORÁ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CERES', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITAPACI', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NOVA CRIXÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'URUAÇU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ITAPIRAPUÃ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ALVORADA DO NORTE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ANICUNS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ARAGARÇAS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'AURILÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BARRO ALTO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'BURITI ALEGRE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CALDAS NOVAS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAMPINORTE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CASTELÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CRISTIANÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CUMARI', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'DAMIANÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'DIORAMA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'DOVERLÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ESTRELA DO NORTE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'FIRMINÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'FORMOSO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GOIANÉSIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GUAPÓ', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GUARINOS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'INHUMAS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'INACIOLÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'JANDAIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'JOVIÂNIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'JUSSARA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MAIRIPOTABA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MARA ROSA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MUNDO NOVO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NIQUELÂNDIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NOVA AURORA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NOVA GLÓRIA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'NOVO BRASIL', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'OUVIDOR', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PALMEIRAS DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CEZARINA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PARANAIGUARA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PETROLINA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PIRENÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PLANALTINA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'POSSE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'RIALMA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'RIO QUENTE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'VICENTINÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'URUANA', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'TRINDADE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'TAQUARAL DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SERRANÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÃO SIMÃO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SÃO DOMINGOS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTO ANTÔNIO DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'PROFESSOR JAMIL', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CIDADE OCIDENTAL', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CHAPADÃO DO CÉU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ALTO HORIZONTE', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'MORRINHOS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'QUIRINÓPOLIS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ÁGUAS LINDAS DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'SANTO ANTÔNIO DO DESCOBERTO', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'ABADIA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'CAMPO LIMPO DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'UIRAPURU', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GAMELEIRA DE GOIÁS', 'GO');
INSERT INTO city (id, name, state) VALUES (uuid_generate_v4(), 'GIRASSOL (COCALZINHO DE GOIÁS)', 'GO');

